spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/headhunter
    password: abdulloh2004@
    username: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update